<a href="https://colab.research.google.com/github/Thannos/Aula8/blob/master/Aula8_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
def gauss(b, a, n, x, k):
  #x = np.zeros(n)
  x[n]=b[n]/a[x][x]
  for j in range (k+1, n):
    s = s + a[k][j] * x[j]
    x[k] = (b[k] - s)/a[k][k]
  return x
#k=(n-1),...,1
a=np.array([[3,2,4], [0, 1/3, 2/3], [0,0,-8]])
b=np.array([1,5/3,0])
for n in range(1,3):
  c=gauss(b,a,3,3, n)
  print("c=\n",c)
  
#terminar em casa

IndexError: ignored

In [36]:
import numpy as np
def triang(a,b,n):
  for k in range(1,(n-1)):
    for i in range ((k+1),n):
      m=a[i,k]/a[k,k]
      a[i,k]=0
      for j in range((k+1),n):
        a[i,j]=a[i,j]-m*a[k,j]
        b[i]=b[i]-m*b[k]
        
  print(a)
m = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])
b = np.array([1,2,3])
print(m)
triang(m,b,3)

[[ 3  2  4]
 [ 1  1  2]
 [ 4  3 -2]]
[[ 3  2  4]
 [ 1  1  2]
 [ 4  0 -8]]
