<a href="https://colab.research.google.com/github/Thannos/Aula8/blob/master/Aula8_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [27]:
def metgauss(a, vet, n, m):
    x = np.zeros((m))
    for k in range(0, m):
        for r in range(k+1,m):
            resp = (a[r,k]/a[k,k])
            vet[r] = vet[r]-(resp*vet[k])
            for c in range(0,n):
                a[r,c] = a[r,c]-(resp*a[k,c])
    x[m - 1] = vet[m-1]/a[m-1, m-1]
    for r in range(m-1, -1, -1): 
        soma = 0
        for c in range(0,n):
            soma = soma + a[r,c]*x[c]
            x[r]=(vet[r]-soma)/a[r,r]
    print('Resultado matriz:\n',a,'\nResultado do vetor:\n',vet,'\nResultados: ',resp)
    
a=np.array([[3.,2.,4.], [0., 1., 2.], [4.,3.,-2.]])
b=np.array([1.,2.,3.])
n=3
m=3
metgauss(a,b,n,m)
#terminar em casa

Resultado matriz:
 [[ 3.  2.  4.]
 [ 0.  1.  2.]
 [ 0.  0. -8.]] 
Resultado do vetor:
 [1. 2. 1.] 
Resultados:  0.3333333333333335


In [18]:
def gaus(a,b,m,n):
    for k in range(0, m): 
        for r in range(k+1,m): 
            resp = (a[r,k]/a[k,k])
            b[r] -= (resp*b[k])
            for c in range(0,n):
                a[r,c] -= (resp*a[k,c])
    for k in range(0, m): 
        for r in range(k+1,m): 
            resp = (a[r,k]/a[k,k])
            b[r] -= (resp*b[k])
            for c in range(0,n):
                a[r,c] -= (resp*a[k,c])
    print('Resultado matriz:\n',a,'\nResultado do vetor:\n',b,'\nResultados: ',resp)
m=3
n=3
a = np.array([[3.,2.,4.], [1.,1.,2.], [4.,3.,-2.]])
b = np.array([1.,2.,3.])
print('matriz:\n',a,'\nvetor:\n',b)
gaus(a, b, m, n)

matriz:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]] 
vetor:
 [1. 2. 3.]
Resultado matriz:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -8.        ]] 
Resultado do vetor:
 [ 1.00000000e+00  1.66666667e+00 -7.21644966e-16] 
Resultados:  1.6653345369377346e-16
